[package]
name = "webapp"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
ybc = "0.4.0"
yew-feather = "1.0"
fluent = "0.16"
unic-langid = { version = "0.9", features = ["macros"] }