[package]
name = "app-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
bdat = "0.4.0"
game-data = { path = "../game-data" }
anyhow = "1.0.72"
enum-map = { version = "2.6" }
recordkeeper = { path = "../lib" }
serde_json = "1.0"
strum = { version = "0.25.0" }
binrw = "0.13"
